### ISSUE TITLE
Rewrite tests to use dart test package

### ISSUE THREAD

**Issue by eknoes** [ra1u/redis-dart#10]
What do you think generally about rewriting the tests, using darts [test](https://pub.dev/packages/test) package?

I think it would provide some improvements, as it makes it easier for new contributors to add & understand existing tests, it makes debugging easier when tests fail and if you like it would be easier to use Continuous Integration tools like Travis.

**Comment by ra1u** [comment]
I think it would be good improvement. 
I am missing configurable address on test server. We also need to remove assert() in testing code.

**Comment by eknoes** [comment]
I began rewriting in a branch: https://github.com/eknoes/redis-dart/tree/migrate-test

**Comment by ra1u** [comment]
Thank you for this patch merged.
