### ISSUE TITLE
Where do you pass the auth password

### ISSUE THREAD

**Issue by Peace-N** [ra1u/redis-dart#17]
Where do you pass the auth password, i see on the connection instance that there is only host and port required .

**Comment by ra1u** [comment]
Following https://redis.io/commands/auth you can auth by sending apropriate command accordingly.

I think that something like

    RedisConnection conn = new RedisConnection();
    conn.connect('localhost',6379).then((Command command){
      command.send_object(["AUTH","<un>","<pass>"])
      .then((var response){
        assert(response == 'OK');
      })
     ...
    });

Or in async style like:

    RedisConnection conn = new RedisConnection();
    Command command = await conn.connect('host',port);
    var response =  await command.send_object(["AUTH","<un>","<pass>"]);
    assert(response == 'OK');

I have not test this, but I hope this works as expected and let me know how this works for you.
Kind regards, Luka,

**Comment by ra1u** [comment]
@Peace-N Can you please update this issue with any progress that you got so far.
