### ISSUE TITLE
How do we connect to an SSL port?

### ISSUE THREAD

**Issue by abhin-vicks** [ra1u/redis-dart#19]
It works fine when I enable non SSL port in my Azure Cache for Redis. But when I enable SSL port 6380, this is the error I get: _E/flutter ( 5132): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address = RedisAbhinav.redis.cache.windows.net, port = 44938_

Code: 

```
RedisConnection conn = new RedisConnection();
    conn
        .connect('SampleName.redis.cache.windows.net', 6380)
        .then((Command command) {
      command.send_object([
        "AUTH",
        "<YourKey>"
      ]).then((var response) {
        print(response);
      });
```

**Comment by ra1u** [comment]
We currently do no support other than raw tcp sockets. However you can
start by subclassing underlaying socket that is constructed in C
onnection. Implementation should not take long but geting right approach
can be more tricky.

I am currently absent from computer for 2 weeks. I can take a look at that
time  if still needed, or if you stuck to make a progress.

Kind regards, Luka.

**Comment by Derrick56007** [comment]
this would be very useful!

**Comment by Derrick56007** [comment]
https://github.com/ra1u/redis-dart/pull/21

created a pr

**Comment by ra1u** [comment]
Implemented in PR and now also released
