### ISSUE TITLE
SocketException while running

### ISSUE THREAD

**Issue by Dewsworld** [ra1u/redis-dart#20]
Hello When I run a simple code

```
void main() async {
  runApp(MyApp());

  RedisConnection conn = new RedisConnection();
  conn.connect('some_production_server_address',6379).then((Command command) {
    PubSub pubsub = new PubSub(command);
    pubsub.getStream().listen((message){
      Fluttertoast.showToast(
          msg: message.toString(),
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.CENTER,
          timeInSecForIosWeb: 1,
          backgroundColor: Colors.red,
          textColor: Colors.white,
          fontSize: 16.0,
      );

      // send object
      command.send_object(["PUBLISH","monkey","banana"]);
    });
  });
}
```

I get this error

`2021-01-12 15:54:38.405 3460-3488/com.dw.flutter_redis_sample E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = some_production_server_address, port = 39609
`

I have added this in the manifest

`<uses-permission android:name="android.permission.INTERNET"/>`

Also, I am using a real device.

I am using port 6379, I am not sure why this port used for 39609 (which also changes each time I restart the app)

**Comment by ra1u** [comment]
Hi @Dewsworld 

It looks like there is an issue with connecting to your server.
Are you able to open raw connection to same server and same port from where application is running?

**Comment by Dewsworld** [comment]
> Hi @Dewsworld
> 
> It looks like there is an issue with connecting to your server.
> Are you able to open raw connection to same server and same port from where application is running?

Can you put some code to do that?

**Comment by ra1u** [comment]
Try to get  valid  `Future<Socket>` when calling

[Socket.connect(host,port)](https://api.dart.dev/stable/2.10.4/dart-io/Socket/connect.html)

You can also take a look at [lib/connection.dart](https://github.com/ra1u/redis-dart/blob/8c858b607d7f03b50495ea558f277be658bcf42f/lib/connection.dart#L21) where might be source of current issue

**Comment by Dewsworld** [comment]
> Try to get valid `Future<Socket>` when calling
> 
> [Socket.connect(host,port)](https://api.dart.dev/stable/2.10.4/dart-io/Socket/connect.html)
> 
> You can also take a look at [lib/connection.dart](https://github.com/ra1u/redis-dart/blob/8c858b607d7f03b50495ea558f277be658bcf42f/lib/connection.dart#L21) where might be source of current issue

Here is the result from log, 

```
[+1463 ms] I/flutter (11057): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[   +1 ms] I/flutter (11057): │ #0   main (package:flutter_redis_sample/main.dart:13:7)
[        ] I/flutter (11057): │ #1   _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:136:25)
[        ] I/flutter (11057): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter (11057): │ 🐛 Instance of 'Future<Socket>'
[        ] I/flutter (11057): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by ra1u** [comment]
It is hard to tell what is going on without more info, but if you are unable to connect to your redis server by using only Socket it is out of scope of this library.
I unfortunately do not have much of experience in flutter, to be able to help you further.

**Comment by Dewsworld** [comment]
Okey, thanks for your effort.

Btw, here is the documents I followed to setup redis. 

https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-18-04

Is there anything I am missing on server side? If you could.

**Comment by ra1u** [comment]
I would start start by investigating why there is "Connection refused"  error message

**Comment by Dewsworld** [comment]
Okey, thanks again for your assistance. Will find something.
