### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by erf** [ra1u/redis-dart#23]
Any plans on migrating to null-safety?

**Comment by ra1u** [comment]
Sound like good idea and it seems that our users who would benefit from this.

@erf have you took a look into what is needed for this and what can we expected?

**Comment by erf** [comment]
You can read and follow the migration guide here:
https://dart.dev/null-safety/migration-guide

As you don't have any dependencies you should be ready to go. Try and set he version to `2.12.0-0` and see what needs to be done. There is also a migration tool.

**Comment by Derrick56007** [comment]
i can take this on

**Comment by Derrick56007** [comment]
https://github.com/ra1u/redis-dart/pull/25

**Comment by ra1u** [comment]
Closed by https://github.com/ra1u/redis-dart/pull/28
