### ISSUE TITLE
Should results return a type and not a string «OK»?

### ISSUE THREAD

**Issue by erf** [ra1u/redis-dart#40]
More of a question, but would it make sense that the api would return a type instead of just the string "OK" ? Or do we just pass the redis types?

**Comment by ra1u** [comment]
I think that OK if I understand correctly is redis response where there is no data to return. so Redis returns OK.
Interpretation is up to user. However this interpretation should be in my opinion handled in particular command. 
For example set() as redis command should return future with type OK, but send_object should in my opinion return whatever is received from redis.

**Comment by erf** [comment]
OK. I agree :)
