### ISSUE TITLE
Redis doesn't work on flutter web

### ISSUE THREAD

**Issue by Ranaco** [ra1u/redis-dart#65]
Redis package don't works on web, this is probably because it somewhere uses dart:io which is not supported on flutter web and the problem is there is no altenative to this!!

**Comment by ra1u** [comment]
I understand you. We have discussion about this https://github.com/ra1u/redis-dart/discussions/27 . Feel free to put your suggestion there and lets find something that can work for your case.

Kind regards, Luka.
