### ISSUE TITLE
Missing compatibility with Dart 2.0 or grater

### ISSUE THREAD

**Issue by igorsiriani** [ra1u/redis-dart#7]
I'm trying to use redis with a Dart API, but my environment is using sdk 2.2.0 and I'm getting version errors. Trying to use `dependency_overrides` did not show any results.

**Comment by ra1u** [comment]
Thank you for your feedback!

I have put redis-dart little bit asides and I got aware of that issue.
I think that [SilverBirchVentures](https://github.com/SilverBirchVentures/redis-dart) put some work into making dart 2.0 support, but I haven't checked that out.
I might put some work into this in near future, but I can not promise anything.

I am also open to accept pull requests.

Cheers, Luka

**Comment by ra1u** [comment]
I am looking for volunteers to test recent patch 4bf859a10b7a39fe25756f0015764b761f7728bc from master.

**Comment by ra1u** [comment]
Recent tag v1.1.0 in also available from pub https://pub.dev/packages/redis
