### ISSUE TITLE
JSON.GET <key> <JSON Path> not working

### ISSUE THREAD

**Issue by tricaricom** [ra1u/redis-dart#79]
Using the Redis-CLI, I can run a JSON.GET query such as 

`JSON.GET h4:9q9h 'd.[?(@.id=="e5dbaa67-c953-4903-bf79-682f82f8c42d")]'`

But when I run this through redis-dart, I get an error such as

`RedisError(JSON Path error: path error: \n$.'d.[?(@.id=="e5dbaa67-c953-4903-bf79-682f82f8c42d")]'\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n)`

It looks like it's adding a `$.` and that may be throwing off the byte boundaries?  Has anyone else experienced this?

My RedisJSON key/value is structured like this

key: `h4:9q9h`

value: `{ d: [ { id: "e5dbaa67-c953-4903-bf79-682f82f8c42d" }, { id: "..." } ] }`

**Comment by ra1u** [comment]
Closed due to inactivity. Please add relevant info as in prevous post to reopen this issue.
