### ISSUE TITLE
Redis dart licence change - Need your Feedback!

### ISSUE THREAD

**Issue by ra1u** [ra1u/redis-dart#82]
To all contributors of this redis-dart package. THIS is important!!!!!! 

We would like to change current licence from [GNU Affero General Public License v3.0](https://github.com/ra1u/redis-dart/blob/86831f284ae2017411bc4e457a1c04beb720e3af/LICENSE) into  [MIT licence](https://github.com/Dart-Code/Flutter/blob/master/LICENSE)

@erf
@eknoes 
@derrick56007
@ArnaudHeywear
@necessarylion
@Gabsop
@evanx

**Why?**

Simply put - Current licence requires that **users disclose all source code**  using this library and sharing such code under the same licence. 
For details follow wiki link https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License and cosult legal department.

How to change?
Please write in comment below that you either

- **you agree** to licence change to MIT licence
- **you do not agree** with licence change and that you would like to keep current licence - GNU Affero General Public License v3.0

Thank you for your feedback and your contribution!

**Comment by eknoes** [comment]
I agree to change the license to MIT license.

**Comment by necessarylion** [comment]
I agree

**Comment by vlidholt** [comment]
I haven't contributed, but I agree. :) This is currently a show stopper for most projects which wants to use this library.

**Comment by erf** [comment]
I agree to license change to MIT license.

**Comment by Silentdoer** [comment]
I haven't contributed, but I agree. :) This is currently a show stopper for most projects which wants to use this library.

**Comment by Silentdoer** [comment]
To modify the open source license of this project, do you have to wait for everyone here @ to agree before you can modify it? Or is there a time limit, for example, if these people do not reply for more than 3 months or half a year, they agree by default, and then they can modify the agreement

**Comment by ra1u** [comment]
Licence in v4.0.0 is now MIT.
Please reach me out if you have reservations againt this or post in this thread.
